### PR TITLE
W_accelerometer

### PR DESCRIPTION
**Pull request by sunwangshu**
Widgetized accelerometer widget based on new template.
Live data and playback data from OpenBCI board working now.
Commented out .setFont because somehow not working here.

major next step:
live and playback from Ganglion need to be implemented.
playback from BDF needs to be implemented.

minor issues:
aesthetic improvements.
improve synthesize acc data.
vertical responsive fix.
Playback initialize buffer not empty when initialize

### CODE REVIEW

**Comment by aj-ptw** [comment]
this is so cool.

**Comment by aj-ptw** [comment]
Hey I'm worried this code will not work if the user chose to output BDF vs the original ODF.

**Comment by sunwangshu** [comment]
Oh right I'm not sure how the other data format work.

**Comment by aj-ptw** [comment]
That's ok, i can try to fix it, I was hoping to go through it with you anyway to get your helping on making it work completely. I think we should merge this.

**Comment by sunwangshu** [comment]
Ok let me know if any question regarding current update and I'll try to explain as I can.

BTW I think I'll update it a little bit since Conor's using the latest version of ControlP5 and the setText() error is not a bug.

**Comment by sunwangshu** [comment]
Reverted setText() back to original and updated ControlP5 library version.

**Comment by aj-ptw** [comment]
Scaling is very strange and this does not seem right. Also was text changed?
screen shot 2016-12-07 at 3 09 40 pm

**Comment by aj-ptw** [comment]
I'm still seeing it here
screen shot 2016-12-07 at 3 09 40 pm

**Comment by aj-ptw** [comment]
I'm still seeing it in the smaller config too 
screen shot 2016-12-07 at 3 11 45 pm

**Comment by sunwangshu** [comment]
Vertical scaling is not yet implemented as stated above. So you are seeing it as it is now. For now the functionality should be fine except I'm not sure about BDF playback.

**Comment by aj-ptw** [comment]
> y axis responsive fix.

Ok so I should drag and drop this controlP5 library to test it?

**Comment by sunwangshu** [comment]
Try sync this branch because I just updated the library.
Then you can drag and drop the OpenBCI_GUI_v2.0/libraries/ControlP5 into your processing libraries folder, test if the text are showing up correctly.
The header font should be looking like this:
screen shot 2016-12-07 at 3 20 46 pm

**Comment by aj-ptw** [comment]
Yea ok we're seeing it now. Will merge now.

**Comment by aj-ptw** [comment]
I also changed your base branch and put it in development. not going to merge this with master just yet, would like to get the y scaling fixed at least.

**Comment by sunwangshu** [comment]
Ok, it was based on development but anyway thanks for checking :)

**Comment by aj-ptw** [comment]
Yup the goal is to keep master stable and nice looking, going to dev first gives us a chance to all try and catch bugs.

**Comment by sunwangshu** [comment]
Yeahh.

**Pull request merged**
